version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: server
    ports:
      - 4000:4000
    volumes:
      - ./src:/app/src
    depends_on:
      - db
      - redis
      - elasticsearch

  db:
    image: postgres
    restart: always
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/app/var/lib/postgresql/data

  dbadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: dbadmin
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: maks@admin.com
      PGADMIN_DEFAULT_PASSWORD: maksadmin
    volumes:
      - ./pgadmin-data:/app/var/lib/pgadmin

  redis:
    image: redis
    restart: unless-stopped
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/app/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: vh-elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=datasearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.initial_master_nodes=elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elastic:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  pgdata:
  pgadmin-data:
  redis:
    driver: local